
name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    strategy:
      matrix:
          platform: [ubuntu-latest]
          node-version: ['20.x']

    runs-on: ${{ matrix.platform }}
    steps:
            
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install and Test Client
          working-directory: ./frontend
          run: |
            npm install
            npm run test
        
        - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.11.0
          with:
            mongodb-version: latest

        - name: Install and Test Server
          env:
            ATLAS_URI: ${{ secrets.ATLAS_URI }}
            TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
            PORT: ${{ secrets.PORT }}
          working-directory: ./backend
          run: |
            npm install
            npm run test
        
        - name: Build Container Stack
          run: docker compose up -d --build

        - name: Test Container Stack
          run: docker run --network container:fitness-ally-frontend-1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
        
        - name: Stop containers
          if: always()
          run: docker compose down

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Push Images to Docker Hub
          run: | 
            docker push christhorne714/fitness-ally:fitnally-frontend-${{github.run_number}}
            docker push christhorne714/fitness-ally:fitnally-backend-${{github.run_number}}