
name: Build and deploy

on:
  push:
    branches:
      - main

env:
  ATLAS_URI: ${{ secrets.ATLAST_URI }}
  TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
  PORT: ${{ secrets.PORT }}

jobs:
  build-and-deploy:
    strategy:
      matrix:
          platform: [macos-latest, windows-latest, ubuntu-latest]
          node-version: ['20.x']

    runs-on: ${{ matrix.platform }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install and Test Client
          working-directory: ./frontend
          run: |
            npm install
            npm run test

        - name: Install and Test Server
          working-directory: ./backend
          run: |
            npm install
            export ATLAS_URI=$ATLAS_URI
            export TOKEN_KEY=$TOKEN_KEY
            export PORT=$PORT
            npm run test

      
